/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package bfds.carpet;

import java.util.Arrays;

public class App {
    public static void main(String[] args) {

        int brown = 
            24;
        int red =
            24;

        Solution s = new Solution();

        System.out.println(Arrays.toString(s.solution(brown, red)));

    }
}
